version: '3.8'

services:
  firefly:
    image: fireflyiii/core:latest
    deploy:
      replicas: 3
    ports:
      - "80:8080"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_KEY: ${APP_KEY}
    networks:
      - firefly_network

networks:
  firefly_network:
    driver: overlay
