---
networks:
  firefly_net:
    driver: overlay
volumes:
  mysql-data: null
  firefly-upload: null
secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  db_user_password:
    file: ./db_user_password.txt
configs:
  nginx_conf:
    file: ./nginx/nginx.conf
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - db_user_password
    networks:
      - firefly_net
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      timeout: 20s
      retries: 10
  firefly:
    image: fireflyiii/core:latest
    deploy:
      replicas: 3
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD_FILE: /run/secrets/db_user_password
      APP_KEY: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      SESSION_DRIVER: file
      CACHE_DRIVER: array
      SESSION_SECURE_COOKIE: 0
      SESSION_LIFETIME: 120
      DB_WAIT_TIMEOUT: 60
    secrets:
      - db_user_password
    volumes:
      - firefly-upload:/var/www/html/storage/upload
    networks:
      firefly_net:
        aliases:
          - firefly
    depends_on:
      - mysql
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/api/v1/about
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
  nginx:
    image: nginx:alpine
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - firefly
    ports:
      - 80:80
    networks:
      - firefly_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure