---
networks:
  firefly_net:
    driver: overlay
volumes:
  mysql-data: null
secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  db_user_password:
    file: ./db_user_password.txt
configs:
  nginx_conf:
    file: ./nginx/nginx.conf
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - db_user_password
    networks:
      - firefly_net
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
  firefly:
    image: fireflyiii/core:latest
    deploy:
      replicas: 3
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD_FILE: /run/secrets/db_user_password
      APP_KEY: ${APP_KEY}
    secrets:
      - db_user_password
    networks:
      firefly_net:
        aliases:
          - firefly
  nginx:
    image: nginx:alpine
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - firefly
    ports:
      - 80:80
    networks:
      - firefly_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure